Number Four
OpenSats/website pull request #113
Opened 2023-07-13 22:14 UTC by dergigi

2023-07-13 22:37 UTC, lucasmogu requested changes

2023-07-13 22:37 UTC, lucasmogu commented on data/blog/bitcoin-grants-july-2023.mdx
> +The following open-source projects were [selected](https://github.com/OpenSats/website/blob/master/docs/grant-selection.md) to by the
were selected by

2023-07-14 00:28 UTC, importantgabe commented on data/blog/bitcoin-grants-july-2023.mdx
> +living in the rural areas of Nigeria.
I would put these descriptions underneath each of the bullet points, it makes it harder to follow when I read the bullet points then see the descriptions below and have to circle back to the bullets.

2023-07-14 00:29 UTC, importantgabe commented on data/blog/bitcoin-grants-july-2023.mdx
> +bring quality Bitcoin education to Russian citizens. Tony and others have been
Might be worthwhile to link to Apata and Tony's Twitter or Nostr profiles, I don't know who they are.

2023-07-14 00:31 UTC, importantgabe commented on data/blog/bitcoin-grants-july-2023.mdx
> +payjoin support in their software. Payjoin Dev Kit makes it easy to integrate
Makes it easy for wallet developers(?). As a non-developer I'm unclear on why this project matters (other than knowing that privacy is important).

2023-07-14 00:38 UTC, importantgabe commented on data/blog/bitcoin-grants-july-2023.mdx
> +focus on usability and user experience. The project's current target audience is
I would start this paragraph off with "Blixt is a non-custodial wallet whose current audience is bitcoiners who want to give Lightning a try". I feel like that draws those potential people in more, and then you can give them details that they may not understand.

2023-07-14 00:39 UTC, importantgabe commented on data/blog/bitcoin-grants-july-2023.mdx
> +Fund](https://opensats.org/projects/general_fund).
My opinion will always be that this should be at the top, before introducing the projects, planting the seed in readers' minds that they can donate to these projects. And then repeat the "soft ask" again at the bottom

2023-07-14 22:20 UTC, merged