Add /transparency page
OpenSats/website pull request #117
Opened 2023-08-07 13:22 UTC by dergigi

Work in progress, as some documents still need to be finalized.

2023-08-23 00:53 UTC, lucasmogu requested changes

2023-08-23 00:53 UTC, lucasmogu commented on data/pages/transparency.mdx
> +responsible sat management, good corporate citizenship, and the long-term
"sat management" - I assume this means bitcoin treasury management. If that's the case, I would prefer to use a more explicit term such as "bitcoin treasury management" or "treasury management" or "donation management".
My concern is that, for now, some or many people may not understand what "sat management" means.

2023-08-23 14:20 UTC, lucasmogu commented on data/pages/transparency.mdx
> +responsible sat management, good corporate citizenship, and the long-term
responsible bitcoin treasury management, good corporate citizenship, and the long-term

2023-08-24 10:34 UTC, dergigi commented on data/pages/transparency.mdx
> +responsible sat management, good corporate citizenship, and the long-term
```suggestion
responsible bitcoin treasury management, good corporate citizenship, and the long-term
```

2023-08-24 10:37 UTC, merged