Update btcpayserver.mdx
OpenSats/website pull request #143
Opened 2023-10-14 08:51 UTC by lucasmogu

Update "summary" and "description" as per OpenSats/volunteers#1

2023-10-14 16:43 UTC, Arvin21M requested changes
@lucasmogu Just some light touch ups. Line 18: I changed **Simple** to **Easy** because you used _Simply_ earlier in the paragraph and I was compelled to request the change, lol. Thank you!

2023-10-14 16:43 UTC, Arvin21M commented on data/projects/btcpayserver.mdx
> +summary: 'Start accepting Bitcoin payments with 0% fees & no third-party.'
```suggestion
summary: 'Start accepting Bitcoin payments with 0% processing fees & no third-party intermediary.'
```

2023-10-14 16:43 UTC, Arvin21M commented on data/projects/btcpayserver.mdx
> +BTCPay Server is a self-hosted, open-source cryptocurrency payment processor. It's secure, private, censorship-resistant, and free. Simply launch a server (cloud, your own hardware device, or an exis
```suggestion
BTCPay Server is a self-hosted, open-source cryptocurrency payment processor. It's secure, private, censorship-resistant, and free. Simply launch a server (cloud, your own hardware device, or an existing host), connect your e-commerce store or one of the many apps, and funds arrive directly to your connected wallet. Ability to also facilitate cross-border transactions without conversion fees. Easy to use with native wallet management, and great for invoicing and accounting.
```

2023-10-15 04:33 UTC, lucasmogu commented
@Arvin21M thanks for the revision, all suggestions for all projects have been committed now. Great to see our GitHub skills improving :)

2023-10-16 10:42 UTC, dergigi approved these changes
Looks good to me ✅

2023-10-16 10:43 UTC, merged