Update ronin_dojo.mdx
OpenSats/website pull request #146
Opened 2023-10-14 09:12 UTC by lucasmogu

Update "summary" and "description" as per OpenSats/volunteers#1

2023-10-14 16:53 UTC, Arvin21M requested changes
Just a few sprinkles of change.

2023-10-14 16:53 UTC, Arvin21M commented on data/projects/ronin_dojo.mdx
> +summary: 'RoninDojo helps bitcoiners have a feature-rich bitcoin experience, maintain privacy, and thrive as sovereign individuals by developing easy-to-use hardware (such as the Tanto full bitcoin n
```suggestion
summary: 'RoninDojo helps Bitcoiners have a feature-rich bitcoin experience, maintain privacy, and thrive as sovereign individuals by developing easy-to-use hardware (such as the Tanto full Bitcoin node) and software (RoninUI which uses TOR by default).'
```

2023-10-14 16:53 UTC, Arvin21M commented on data/projects/ronin_dojo.mdx
> +RoninDojo products include Bitcoin nodes, steel backup plates, powerful storage, premium support, and much more coming soon. RoninDojo works hard to increase accessibility for bitcoiners to connect t
```suggestion
RoninDojo products include Bitcoin nodes, steel backup plates, powerful storage, premium support, and much more coming soon. RoninDojo works hard to increase accessibility for Bitcoiners to connect their wallet to a node, use privacy-enhancing CoinJoin, and do self-custody.
```

2023-10-16 10:52 UTC, dergigi requested changes

2023-10-16 10:52 UTC, dergigi commented on data/projects/ronin_dojo.mdx
> +RoninDojo products include Bitcoin nodes, steel backup plates, powerful storage, premium support, and much more coming soon. RoninDojo works hard to increase accessibility for Bitcoiners to connect t
I don't think we should focus on the product side of this project, but on the fact that this is an open-source operating system that can run on many different devices: https://code.samourai.io/ronindojo/RoninOS

2024-01-15 19:03 UTC, closed without merging