Update sapio.mdx
OpenSats/website pull request #147
Opened 2023-10-14 09:16 UTC by lucasmogu

Update "summary" and "description" as per OpenSats/volunteers#1

2023-10-14 17:05 UTC, Arvin21M requested changes

2023-10-14 17:05 UTC, Arvin21M commented on data/projects/sapio.mdx
> +For example, with Sapio you can generate an address that represents a lightning channel between you and a friend and give that address to a third-party service like an exchange and have them create t
```suggestion
For example, with Sapio you can generate an address that represents a Lightning channel between you and a friend, then give that address to a third-party service like an exchange to have them create the channel without requiring any signature interaction from you or your friend, using zero trusted parties, and an inability to differentiate your address from any other. That’s the tip of the iceberg of what Sapio lets you accomplish.
```

2023-10-14 17:05 UTC, Arvin21M commented on data/projects/sapio.mdx
> +Before Sapio, most Bitcoin smart contracts primarily focused on who could redeem coins when and what unlocking conditions were required (see Ivy, Policy/Miniscript, etc.). A few languages, such as Bi
```suggestion
Before Sapio, most Bitcoin smart contracts primarily focused on who could redeem coins when, and what unlocking conditions were required (see Ivy, Policy/Miniscript, etc.). A few languages, such as BitML, emphasized multi-transaction and multi-party use cases. Sapio in particular focuses on transactions using BIP-119 OP_CHECKTEMPLATEVERIFY. OP_CHECKTEMPLATEVERIFY enables Bitcoin Script to support complex multi-step smart contracts without a trusted setup.
```

2023-10-14 17:05 UTC, Arvin21M commented on data/projects/sapio.mdx
> +Sapio is a tool for easily defining such smart contracts and exporting easy-to-integrate APIs for managing open contracts. With Sapio you can turn what previously would require months or years of car
```suggestion
Sapio is a tool for easily defining such smart contracts and exporting easy-to-integrate APIs for managing open contracts. With Sapio you can turn what previously would require months or years of careful tinkering with Bitcoin internals into a 20-minute project to get a fully functional Bitcoin application.
```

2023-10-16 10:55 UTC, dergigi requested changes
I've added some markdown formatting for `OP_CHECKTEMPLATEVERIFY` and a link to [BIP-119](https://utxos.org/). 

You should be able to accept my suggested change with one click.

2023-10-16 10:55 UTC, dergigi commented on data/projects/sapio.mdx
> +Before Sapio, most Bitcoin smart contracts primarily focused on who could redeem coins when, and what unlocking conditions were required (see Ivy, Policy/Miniscript, etc.). A few languages, such as B
```suggestion
Before Sapio, most Bitcoin smart contracts primarily focused on who could redeem coins when, and what unlocking conditions were required (see Ivy, Policy/Miniscript, etc.). A few languages, such as BitML, emphasized multi-transaction and multi-party use cases. Sapio in particular focuses on transactions using [BIP-119](https://utxos.org/) `OP_CHECKTEMPLATEVERIFY`. `OP_CHECKTEMPLATEVERIFY` enables Bitcoin Script to support complex multi-step smart contracts without a trusted setup.
```

2023-10-17 12:35 UTC, Arvin21M approved these changes

2023-11-02 23:10 UTC, dergigi approved these changes
Looks good to me ✅

2023-11-02 23:18 UTC, merged