Update summerofbitcoin.mdx
OpenSats/website pull request #149
Opened 2023-10-14 09:30 UTC by lucasmogu

Update "summary" and "description" as per OpenSats/volunteers#1

2023-10-14 17:12 UTC, Arvin21M requested changes

2023-10-14 17:12 UTC, Arvin21M commented on data/projects/summerofbitcoin.mdx
> +Interested students apply to a program track (Developer or Designer) based on their background and go through a screening round. Screened students learn how Bitcoin works from a curated set of resour
```suggestion
Interested students apply to a program track (Developer or Designer) based on their background and go through a screening round. Screened students learn how Bitcoin works from a curated set of resources and submit a project proposal. Accepted students contribute to Bitcoin open-source projects. Students who perform exceptionally well are referred for a career in Bitcoin. Over 50K+ lines of open-source code have been contributed by students!
```

2023-10-16 10:59 UTC, dergigi reviewed
I feel like the previous description was better 😅

2023-10-17 02:09 UTC, lucasmogu commented
All good, I'll close this PR now without merging it.

2023-10-17 02:09 UTC, closed without merging