Add sats denomination to donation form
OpenSats/website pull request #185
Opened 2023-11-24 15:05 UTC by Bayernatoor

Hello everyone! This pull request addresses issue #41 

Changes made: 

1. Adds a `SATS` and `USD` toggle infront of the preset donation amounts
2. Input field accepts an amount in satoshi if toggle is set to `SATS`. 
3. If `SATS` is used, amount is first converted to `BTC` format before being added to the `/api/btcpay` `POST` request. `BTC` invoice payload currency field will be set to `BTC` if `sats` are used, otherwise defaults to `USD`.
4. Refactored conditional logic in `useEffect` on `DonationForm` component used to set btc/fiat payment buttons valid
5. Changed `Object.assign` for payload creation to use the spread syntax to accommodate my changes and enhance readability.

<img src="https://github.com/OpenSats/website/assets/55212954/2a3f8a0d-35f9-40d8-be23-d22303d56dd8" width="250" height="75">
<br>
<img src="https://github.com/OpenSats/website/assets/55212954/03b3c323-eebb-4374-ac89-3e11515b49cc" width="250" height="75">
<br>

Notes:
1. I've tested this locally and the payload/post requests appear to be working as intended but I cannot fully it test it as I do not have the capability of making calls to the BtcPay Server or to Stripe checkout (no changes made to USD donations). 
3. Since this impacts users' ability to donate it would be great if a couple people could review and test. As far as I can tell this mimics the current production build however I have tighten up client side validation of the amount being passed (e.g. cannot submit an amount of 0). 

If you have any suggestions/remarks or need clarification on some of the changes I made, please let me know :)

2023-11-28 10:59 UTC, dergigi requested changes
Nice! 

Maybe write `100k` instead of `100,000 sats` so that the buttons remain small and one-line? Also, the text in the input field overlaps with the `sats` prefix, so this needs more padding (or margin) to the right.

<img width="623" alt="Screenshot 2023-11-28 at 10 57 29" src="https://github.com/OpenSats/website/assets/109058/136c2b13-df91-4784-b663-33c920756d05">

2023-11-28 11:12 UTC, Bayernatoor commented
> Nice!
> 
> Maybe write `100k` instead of `100,000 sats` so that the buttons remain small and one-line? Also, the text in the input field overlaps with the `sats` prefix, so this needs more padding (or margin) to the right.
> 

Yeah, I was hesitating on what would look best. How's this: 

![image](https://github.com/OpenSats/website/assets/55212954/8e59209c-8ff6-4bd5-99f0-f876ac140ce5)

As for the Sats on the left side. For some reason I can't see that or the $ sign (I might be missing some font locally). I did opt for the word sat instead of a symbol since, I do not know if there's a universally accepted one yet. Seems like [bitcoin.design](https://bitcoin.design/guide/designing-products/units-and-symbols/#current-adoption) does recommend the word "sat".

I tested the vercel version above and all seems to work except that the btc amount is not being set on the BtcPay Server page. Perhaps we have to enable "BTC" as a supported currency on our btcpay side in order to pass it in the payload?

2023-12-03 14:26 UTC, Bayernatoor reviewed
Yeah, I was hesitating on what would look best. Fixed!

Also, I did opt for the word sat instead of a symbol since, I do not know if there's a universally accepted one yet. Seems like [bitcoin.design](https://bitcoin.design/guide/designing-products/units-and-symbols/#current-adoption) does recommend the word "sat".

I tested the vercel version above and all seems to work except that the bitcoin amount is not being set on the BtcPay Server page. Perhaps we have to enable "BTC" as a supported currency on our btcpay server  in order to pass it in the payload?

2023-12-14 10:18 UTC, Bayernatoor commented
@dergigi When you get a chance can you deploy another staging version of this branch? I want to make sure all looks good and test the btcpay server flow.

2023-12-20 13:53 UTC, Bayernatoor reviewed
Ignore this comment

2024-01-15 19:05 UTC, dergigi commented
I just had another look at this, and unfortunately I found out that we can't easily add this feature without introducing a ton of headaches for accounting.

I'll close this PR for now. We might be able to revisit it at a later point.

2024-01-15 19:05 UTC, closed without merging