Update "About OpenSats" Section
OpenSats/website pull request #219
Opened 2024-02-06 22:57 UTC by dergigi

Also made a small change to the volunteer bios. Clicking on "Volunteer" now brings you to [/about#volunteers](https://opensats.org/about#volunteers).

2024-02-06 23:47 UTC, lucasmogu requested changes

2024-02-06 23:47 UTC, lucasmogu commented on data/authors/charles.mdx
>  occupation: Chief Fiat Officer
```suggestion
occupation: Volunteer
```

2024-02-06 23:56 UTC, dergigi commented on data/authors/charles.mdx
>  occupation: Chief Fiat Officer
Oh, good catch!

2024-02-07 00:06 UTC, lucasmogu approved these changes

2024-02-07 00:06 UTC, merged