Blog Post: 5th Wave of Nostr Grants
OpenSats/website pull request #288
Opened 2024-07-11 15:44 UTC by dergigi

TBD

2024-07-11 16:40 UTC, Arvin21M requested changes
btcschellingpt >> jason for this one 🙏 
Reference:
https://github.com/OpenSats/volunteers/issues/34#issuecomment-2191250757

2024-07-11 16:40 UTC, Arvin21M commented on data/blog/nostr-grants-july-2024.mdx
> +authors: ['arvin', 'btcschellingpt']
```suggestion
authors: ['arvin', 'jason']
```

2024-07-15 14:17 UTC, Arvin21M approved these changes
- Checked all links, they work and point to the right destination. 
- You clearly improved the intro quite a bit, so thank you for helping Jason and I look better 😄 
- Table of content links move page down to proper placement according to the headers.
- Image looks great, though I am really curious about that nostr code in the background of the image.
- Good to go! 🚀

2024-07-15 14:26 UTC, dergigi commented
It's the `event` description of [NIP-01](https://github.com/nostr-protocol/nips/blob/master/01.md):


```jsonc
{
  "id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>,
  "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,
  "created_at": <unix timestamp in seconds>,
  "kind": <integer between 0 and 65535>,
  "tags": [
    [<arbitrary string>...],
    // ...
  ],
  "content": <arbitrary string>,
  "sig": <64-bytes lowercase hex of the signature of the sha256 hash of the serialized event data, which is the same as the "id" field>
}
```

;)

2024-07-15 14:27 UTC, merged

2024-07-15 14:49 UTC, dergigi commented
Live!

- https://opensats.org/blog/nostr-grants-july-2024
- TBD