Blog Post: fiatjaf Nostr LTS
OpenSats/website pull request #293
Opened 2024-07-19 22:07 UTC by Arvin21M

TBD

2024-07-20 19:02 UTC, dergigi requested changes
Some minor edits and suggestions.

2024-07-20 19:02 UTC, dergigi commented on data/blog/fiatjaf-recieves-lts-grant.mdx
> +This LTS grant will enable fiatjaf to continue to improve the functionality and resilience of nostr through several ongoing projects, such as
```suggestion
This LTS grant will enable fiatjaf to focus all his time and attention on nostr and his many ongoing projects, such as 
```

2024-07-20 19:02 UTC, dergigi commented on data/blog/fiatjaf-recieves-lts-grant.mdx
> +[song](https://git.fiatjaf.com/song), [mmm](https://git.fiatjaf.com/mmm), and [promenade](https://git.fiatjaf.com/promenade). These tools and frameworks are essential for the
```suggestion
[song](https://git.fiatjaf.com/song), [mmm](https://git.fiatjaf.com/mmm), and [promenade](https://git.fiatjaf.com/promenade). These tools and frameworks are aimed at improving the 
```

2024-07-20 19:02 UTC, dergigi commented on data/blog/fiatjaf-recieves-lts-grant.mdx
> +-   NIP29 GTK4 desktop client
```suggestion
-   NIP-29 GTK4 desktop client
```

2024-07-21 14:48 UTC, Arvin21M commented
@dergigi these two commit checks are not passing:

[Commit 1](https://github.com/OpenSats/website/pull/293/commits/bb886648cd565dac6d401038491504b2ab5372c7)
[Commit 2](https://github.com/OpenSats/website/pull/293/commits/dd1a70627aebfe7304837681704c4ff8d50ed1c9)

The system is outling the issue with both to be:

> The following actions uses Node.js version which is deprecated and will be forced to run on node20

But when I look at the workflow file for the others that passed checks, they have the same identical file. I am a bit perplexed at this point on how to resolve the failed checks.

2024-07-22 14:31 UTC, dergigi commented
@Arvin21M if you click on the little "x" you will see why:

> Canceled by a more recent commit in the same branch

So that's normal and there's nothing to worry about.

2024-07-22 15:00 UTC, Arvin21M commented
Ah I see. Got it!

> if you click on the little "x" you will see why

2024-07-23 13:24 UTC, merged

2024-07-23 13:36 UTC, dergigi commented
Live now:
- https://opensats.org/blog/fiatjaf-receives-lts-grant
- [nostr post](https://njump.me/nevent1qqsycef79crjaek3t72ajsv2nu3zfh5dzf9q6wlmyqwfw3xfnl8slfczypu8xwr40lp96ewdj2fef408wy70gd3carf9n6xu7hrnhq6whpglyeqdhgy)