Blog Post: Seventh Wave of Nostr Grants
OpenSats/website pull request #323
Opened 2024-09-17 16:57 UTC by Arvin21M

**Build Preview:**
- TODO

**Social Preview:**
- TODO

2024-09-17 21:51 UTC, btcschellingpt approved these changes
Reads well and all links checked and working; good work on the refocus of JeffG's activities within this wave.

Good to go!

2024-09-18 00:27 UTC, erskingardner commented
I would remove the last paragraph of the section on me. The one on ostrich.work and ndk. I'm still helping on ndk but my focus is almost entirely on the messaging stuff

2024-09-19 01:23 UTC, btcschellingpt commented
> I would remove the last paragraph of the section on me. The one on ostrich.work and ndk. I'm still helping on ndk but my focus is almost entirely on the messaging stuff

That was my takeaway from listening to your sessions in Riga Jeff! :-)

2024-09-19 16:03 UTC, dergigi commented
Made some edits, so I'd appreciate a quick sanity check from one of the @OpenSats/volunteers :pray:

2024-09-19 17:00 UTC, Bayernatoor commented on data/blog/7th-wave-of-nostr-grants.mdx
> +Network zaps to enhance secure and decentralized communication.
```suggestion
Network zaps to enhance secure and decentralized communication.
```

2024-09-19 17:03 UTC, Bayernatoor requested changes
Added 1 suggestion, the ending of that sentence seemed a bit off. 

Besides that all links work and everything else reads well! Good job guys. Awesome projects being supported here :orange_heart:

2024-09-19 17:03 UTC, Bayernatoor commented on data/blog/7th-wave-of-nostr-grants.mdx
> +Network zaps to enhance secure and decentralized communication.
```suggestion
Network zaps with the aim of improving security and further decentralizing communications.
```

2024-09-19 17:46 UTC, dergigi approved these changes
Looks good to me. Let's ship it 🐿️

2024-09-19 17:47 UTC, merged