Blog Post: Seventh Wave of Bitcoin Grants
OpenSats/website pull request #325
Opened 2024-09-20 15:16 UTC by Arvin21M

**Build Preview:**

- TODO

**Social Preview:**

- TODO

2024-09-22 14:30 UTC, Arvin21M commented
@OpenSats/volunteers Team, would some one please mind doing a quick sanity check on this when you have a moment? Would like to publish this Monday or Tuesday this week. 🙏

2024-09-23 10:19 UTC, Bayernatoor requested changes
Left a couple suggestions/corrections.

Besides those, everything looks good and all links are correct/work. 

Good job guys! :clap:

2024-09-23 10:19 UTC, Bayernatoor commented on data/blog/seventh-wave-of-bitcoin-grants.mdx
> +and privacy claims to the test in real-world scenarios
```suggestion
and privacy claims to the test in real-world scenarios.
```

2024-09-23 10:19 UTC, Bayernatoor commented on data/blog/seventh-wave-of-bitcoin-grants.mdx
> +storage, and Oracle integration, dlcdevkit enables seamless application
```suggestion
storage, and Oracle integration, dlc dev kit enables seamless application
```

2024-09-23 10:19 UTC, Bayernatoor commented on data/blog/seventh-wave-of-bitcoin-grants.mdx
> +Cove is a mobile wallet built with BDK. Designed for simplicity and
```suggestion
Cove is a mobile wallet built with [BDK](https://github.com/bitcoindevkit/bdk/blob/master/README.md). Designed for simplicity and
```

2024-09-23 20:50 UTC, btcschellingpt commented
Apologies for the lateness of this feedback .. The reference to AssumeUTXO "in BCA"

Where did "Bitcoin Core App" come from? Is this a reference to the new Bitcoin Core QML Gui (which is implied from the author commit link)? By referencing this as "BCA" it's unclear if this is a new "project" from the developer or part of core (which I think it is).

2024-09-24 14:26 UTC, dergigi commented
> Where did "Bitcoin Core App" come from? Is this a reference to the new Bitcoin Core QML Gui (which is implied from the author commit link)?

@btcschellingpt I've added a link which should clear this up:

> This project aims to integrate Assume UTXO functionality into the [Bitcoin Core App](https://bitcoincore.app/) (BCA) [...]

---

The announcement looks good to me, so I'll push this live soon :shipit: 

Thanks for the feedback and the edits everyone 🙏🧡

2024-09-24 14:34 UTC, dergigi approved these changes
Looks good to me ✅

2024-09-24 14:34 UTC, dergigi approved these changes
Looks good to me ✅

2024-09-24 14:34 UTC, merged

2024-09-24 14:53 UTC, dergigi commented
Live now!
- https://opensats.org/blog/bitcoin-grants-september-2024-7th-wave
- [nostr post](https://njump.me/nevent1qqsdueqvqfhprzh74jpldr2vl4g6emfpwmnsdnn7407cxqjsfwe3nnspz3mhxue69uhhyetvv9ujuerpd46hxtnfduq3vamnwvaz7tmjv4kxz7fwwpexjmtpdshxuet5qgs8suecw4luyht9ekff89x4uacneapk8r5dyk0gmn6uwwurf6u9rus3mhcnh)